### ISSUE TITLE
FTDI / OpenOCD / JTAG

### ISSUE THREAD

**Issue by androegg** [marvell-iot/ez-connect-lite#3]
sorry to bother but since Apple starts turning OS X into playground ... some issues appear especially around kext

So i followed your guide but after unloading Apple FTDI Driver I am not able getting a FTDI running on Yosemite also El Capitan. I know recommendation comes from OpenOCD but from my opinion something is wrong because any kind of FTDI Driver is effected within Option permanently.

Guess have to jump on MAKERVILLE KNIT because of AzureWave EVB is based on FTDI?

**Comment by anujdeshpande** [comment]
@androegg It is indeed a pain, but it usually works. If possible do share the output of `uname -a` so that I can try it on a similarly spec'd machine. I have tried it on my MBP and it seems to work fine

```
➜  ~ uname -a
Darwin Anujs-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```

Another thing that you can do is use the ST Link debugger. It's an extremely low cost option to give you full JTAG (hence openocd and gdb) support. 
It's on Adafruit [here](https://www.adafruit.com/products/2548) for $12. I have personally bought it from Aliexpress for as low as $2-3. 

The best part is that the SDK supports it as an alternative interface while flashing/debugging as opposed to the default interface (ftdi)
Hope this helps !

**Comment by androegg** [comment]
@anujdeshpande thank you for quick response I tried it on iMac with Yosemite and also on Mac Pro with El Capitan here specs of Mac Pro

`Darwin Markus-iMac.fritz.box 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64`

I tried 
by using macports also brew
also deinstalled and reinstalled macports and brew
also usblib

Your mentioned alternative with another interface sounds good, I have PL2303 and CH340G running. But I could only find pinmap based on your MAKERVILLE KNIT not AzureWave EVB. Also I guess Pin's will be in standard not in function 1 mode / UART? 

Thank You

**Comment by anujdeshpande** [comment]
@androegg  The Azurewave folks have released a module [datasheet](http://media.wix.com/ugd/1c6751_e949b96ca769452983bca841c92c869c.pdf) on their product page [here](http://www.buyiot.net/#!pd/m7m92) 
 Since Knit is based off the same module/IC as the Azurewave EVB, the pinmux will be the same. The only thing that will be different is the physical position of the pins on the development board.

**Comment by androegg** [comment]
@anujdeshpande first I have to say THANK YOU
Later on I will try connecting by using UART. Maybe Pins will be in UART Function, otherwise I will wait until next week after receiving Knit ;-). So don't go crazy about FTDI since Apple turned into Playground you can spend days on those problems - not worth it -. 
Anuj, Thank You very much!!!
